# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='usertrac.proto',
  package='com.langtaojin.adgaga.tclog',
  serialized_pb='\n\x0eusertrac.proto\x12\x1b\x63om.langtaojin.adgaga.tclog\"\xa9\x02\n\x08UserTrac\x12\x10\n\x08\x63lick_id\x18\x01 \x01(\t\x12\x0c\n\x04muid\x18\x02 \x01(\t\x12\x0c\n\x04xxid\x18\x03 \x01(\t\x12\x11\n\tutrac_eid\x18\x04 \x01(\x05\x12\x12\n\nis_landing\x18\x05 \x01(\x08\x12\x12\n\nis_from_ad\x18\x06 \x01(\x08\x12\n\n\x02ip\x18\x07 \x01(\r\x12\x0c\n\x04time\x18\x08 \x01(\r\x12\x11\n\tchar_code\x18\t \x01(\t\x12\x12\n\nresolution\x18\n \x01(\t\x12\x13\n\x0b\x63olor_depth\x18\x0b \x01(\t\x12\x12\n\npage_title\x18\x0c \x01(\t\x12\x10\n\x08page_url\x18\r \x01(\t\x12\x11\n\tpage_host\x18\x0e \x01(\t\x12\x11\n\tpage_path\x18\x0f \x01(\t\x12\x12\n\nclick_hash\x18\x10 \x01(\t')




_USERTRAC = descriptor.Descriptor(
  name='UserTrac',
  full_name='com.langtaojin.adgaga.tclog.UserTrac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='click_id', full_name='com.langtaojin.adgaga.tclog.UserTrac.click_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='muid', full_name='com.langtaojin.adgaga.tclog.UserTrac.muid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xxid', full_name='com.langtaojin.adgaga.tclog.UserTrac.xxid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='utrac_eid', full_name='com.langtaojin.adgaga.tclog.UserTrac.utrac_eid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_landing', full_name='com.langtaojin.adgaga.tclog.UserTrac.is_landing', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_from_ad', full_name='com.langtaojin.adgaga.tclog.UserTrac.is_from_ad', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='com.langtaojin.adgaga.tclog.UserTrac.ip', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='com.langtaojin.adgaga.tclog.UserTrac.time', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='char_code', full_name='com.langtaojin.adgaga.tclog.UserTrac.char_code', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resolution', full_name='com.langtaojin.adgaga.tclog.UserTrac.resolution', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='color_depth', full_name='com.langtaojin.adgaga.tclog.UserTrac.color_depth', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page_title', full_name='com.langtaojin.adgaga.tclog.UserTrac.page_title', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page_url', full_name='com.langtaojin.adgaga.tclog.UserTrac.page_url', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page_host', full_name='com.langtaojin.adgaga.tclog.UserTrac.page_host', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='page_path', full_name='com.langtaojin.adgaga.tclog.UserTrac.page_path', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='click_hash', full_name='com.langtaojin.adgaga.tclog.UserTrac.click_hash', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=345,
)



class UserTrac(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERTRAC
  
  # @@protoc_insertion_point(class_scope:com.langtaojin.adgaga.tclog.UserTrac)

# @@protoc_insertion_point(module_scope)
